name: Publish docker image to ECR
description: |
  Required secrets:

on:
  workflow_call:
    inputs:
      dockerfile_path:
        type: string
        default: "./Dockerfile"
        description: "Path to a Dockerfile"
      repository_name:
        type: string
        required: true
        description: "Path to a Dockerfile"
      tag:
        type: string
        required: true
        description: "Path to a Dockerfile"
    secrets:
      aws_account_id:
        type: string
        required: true
        description: "AWS account of ECR repository"
      aws_region:
        type: string
        default: eu-north-1
        desceription: "AWS region of ECR"
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    concurrency: "terraform"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume: ${{ secrets.ROLE_ARN }}
            aws-region: ${{ secrets.AWS_REGION }}
      - name: Set up JDK
        uses: actions/setup-java@v2
      - name: Set up gradle
        uses: gradle/gradle-build-action@v2.1.3
      - name: Set up Docker
        run: sudo apt install docker
      - name: Build docker image
        run: docker build -t action-image ${{inputs.dockerfile_path}}
      - name: Login to AWS ECR
        run: aws ecr get-login-password --region ${{secrets.aws_region}} | docker login --username AWS --password-stdin ${{secrets.aws_account_id}}.dkr.ecr.${{secrets.aws_region}}.amazonaws.com
      - name: Publish the image
      - run: docker push "${{secrets.aws_account_id}}.dkr.ecr.${{secrets.aws_region}}.amazonaws.com/${{inputs.repository_name}}:${{inputs.tag}}"
