name: Terraform steps GCP
on:
  workflow_call:
    inputs:
      ### Terraform ###
      base_path:
        default: "./terraform"
        type: string
        required: false
        description: "Base path to terraform folder"
      workspace:
        type: string
        required: true
        description: "Workspace to run terraform on"
      plan_only:
        default: false
        type: boolean
        required: false
        description: "If true runs only plan"
      terraform_version:
        default: '1.2.5'
        type: string
        required: false
        description: "Terraform version"
      tfvars_dir:
        default: ''
        type: string
        required: false
        description: "Terraform tfvars directory to be copied"
      ### GCP ###
      pool_name:
        default: 'github'
        type: string
        required: false
        description: "GCP Workload Identity Pool Name"
      provider_name:
        default: 'github'
        type: string
        required: false
        description: "GCP Workload Identity Pool Provider Name"
      service_account:
        required: true
        type: string
      project_id:
        required: true
        type: string
jobs:
  make_dir_list:
    name: "Get list of terraform directories"
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    outputs:
      directories: ${{steps.list.outputs.list}}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v2
      - name: Construct dir list
        id: list
        run: |
          cd ${{inputs.base_path}}
          for step in ./*; do
          if [ "$step" == "./GLOBAL" ]; then
              continue
          fi
          if [ -n "$result" ]; then
          result="$result,"
          fi
          result="$result\"$step\""
          done
          
          echo "$result"
          echo ::set-output name=list::"{\"terraform-dir\":[$result]}"
  plan:
    if: ${{inputs.plan_only}}
    needs:
      - make_dir_list
    runs-on: ubuntu-latest
    environment: ${{inputs.workspace}}
    permissions:
      id-token: write
      contents: read
    strategy:
      max-parallel: 1
      matrix: ${{fromJson(inputs.directories)}}
    concurrency: "terraform"
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/${{inputs.project_id}}/locations/global/workloadIdentityPools/${{inputs.pool_name}}/providers/${{inputs.provider_name}}
          service_account: ${{inputs.service_account}}
          token_format: 'access_token'
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{inputs.terraform_version}}
      - name: Plan Terraform
        working-directory: ${{inputs.base_path}}/${{matrix.terraform-dir}}
        run: |
          cp -a ../GLOBAL/SHARED/. ./
          if [ -n "${{inputs.tfvars_dir}}" ]; then
          cp -a ../GLOBAL/${{inputs.tfvars_dir}}/. ./
          fi
          terraform init
          terraform workspace select ${{inputs.workspace}} || terraform workspace new ${{inputs.workspace}}
          terraform plan -input=false
  apply:
    if: ${{!inputs.plan_only}}
    needs:
      - make_dir_list
    runs-on: ubuntu-latest
    environment: ${{inputs.workspace}}
    permissions:
      id-token: write
      contents: read
    strategy:
      max-parallel: 1
      matrix: ${{fromJson(needs.make_dir_list.outputs.directories)}}
    concurrency: "terraform"
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/${{inputs.project_id}}/locations/global/workloadIdentityPools/${{inputs.pool_name}}/providers/${{inputs.provider_name}}
          service_account: ${{inputs.service_account}}
          token_format: 'access_token'
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{inputs.terraform_version}}
      - name: Apply Terraform
        working-directory: ${{inputs.base_path}}/${{matrix.terraform-dir}}
        run: |
          cp -a ../GLOBAL/SHARED/. ./
          if [ -n "${{inputs.tfvars_dir}}" ]; then
          cp -a ../GLOBAL/${{inputs.tfvars_dir}}/. ./
          fi
          terraform init
          terraform workspace select ${{inputs.workspace}} || terraform workspace new ${{inputs.workspace}}
          terraform apply -input=false -auto-approve