name: Test Gradle Java Application
on:
  workflow_call:
    inputs:
      artifact_name:
        default: "Unnamed Report "
        type: string
        required: false
        description: "Artifact name"
      artifact_path:
        type: string
        required: false
        description: "Report path to upload"
      task:
        required: true
        type: string
        description: "Command to run"
      java_version:
        type: number
        default: 17
        required: false
        description: "Java version to use"
      java_distro:
        type: string
        required: false
        default: 'temurin'
        description: "Java jdk distributor"
jobs:
  test:
    name: Running gradle task
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: ${{inputs.java_distro}}
          java-version: ${{inputs.java_version}}
      - name: "Run tests"
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: ${{inputs.task}}
      - name: "Upload reports"
        uses: actions/upload-artifact@v3
        with:
          name: ${{inputs.report_name}}
          path: ${{inputs.report_path}}
