name: Test Gradle Java Application
on:
  workflow_call:
    inputs:
      java_version:
        type: number
        default: 17
        required: false
        description: "Java version to use"
      java_distro:
        type: string
        required: false
        default: 'temurin'
        description: "Java jdk distributor"
jobs:
  test:
    name: Testing Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: ${{inputs.java_distro}}
          java-version: ${{inputs.java_version}}
      - name: Run tests
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: test
